<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RiftCtrl</AssemblyName>
    <Product>RIFT//CTRL</Product>
    <ApplicationIcon>Assets\riftctrl.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\riftctrl-icon.png" />
    <Resource Include="Assets\riftctrl.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AssetsTools.NET.Texture" Version="3.*" />
    <PackageReference Include="StbImageWriteSharp" Version="1.16.7" />
    <PackageReference Include="ToolGood.Words.Pinyin" Version="3.1.0.4" />
  </ItemGroup>
</Project>
